ALTER TYPE "JournalSourceType" ADD VALUE IF NOT EXISTS 'SALES_DELIVERY_COGS';
ALTER TYPE "JournalSourceType" ADD VALUE IF NOT EXISTS 'SALES_DELIVERY_COGS_REVERSAL';
ALTER TYPE "JournalSourceType" ADD VALUE IF NOT EXISTS 'SALES_INVOICE_AR';
ALTER TYPE "JournalSourceType" ADD VALUE IF NOT EXISTS 'SALES_INVOICE_AR_REVERSAL';
