import {
  CrmActivityType,
  CrmConversationStatus,
  CrmCustomerSegment,
  CrmCustomerStatus,
  CrmDealStage,
  CrmDealStatus,
  CrmEmployeeRange,
  CrmGender,
  CrmIndustry,
  CrmLeadPriority,
  CrmLeadSource,
  CrmLeadStage,
  CrmLeadStatus,
  CrmMessageStatus,
  CrmTaskPriority,
  CrmTaskStatus,
  type PrismaClient,
} from "../generated/prisma/index.js";

type CrmSeedUser = {
  id: string;
  name: string | null;
};

type CrmSeedInput = {
  db: PrismaClient;
  salesChief: CrmSeedUser;
  salesStaff1: CrmSeedUser;
  salesStaff2: CrmSeedUser;
  director: CrmSeedUser;
  adminChief: CrmSeedUser;
};

function buildSeedDataUrl(label: string) {
  return `data:text/plain;charset=utf-8,${encodeURIComponent(`Lampiran demo CRM: ${label}`)}`;
}

function mapSeedLeadStage(status: CrmLeadStatus): CrmLeadStage {
  switch (status) {
    case CrmLeadStatus.QUALIFIED:
    case CrmLeadStatus.CONVERTED:
      return CrmLeadStage.QUALIFIED;
    case CrmLeadStatus.UNQUALIFIED:
    case CrmLeadStatus.JUNK:
      return CrmLeadStage.LOST;
    case CrmLeadStatus.NEW:
    case CrmLeadStatus.CONTACTED:
    case CrmLeadStatus.NURTURE:
    default:
      return CrmLeadStage.NEW;
  }
}

function mapSeedDealStage(status: CrmDealStatus): CrmDealStage {
  switch (status) {
    case CrmDealStatus.PROPOSAL_QUOTATION:
      return CrmDealStage.PROPOSAL;
    case CrmDealStatus.NEGOTIATION:
      return CrmDealStage.NEGOTIATION;
    case CrmDealStatus.READY_TO_CLOSE:
      return CrmDealStage.VERBAL_WON;
    case CrmDealStatus.WON:
      return CrmDealStage.WON;
    case CrmDealStatus.LOST:
      return CrmDealStage.LOST;
    case CrmDealStatus.QUALIFICATION:
    case CrmDealStatus.DEMO_MAKING:
    default:
      return CrmDealStage.DISCOVERY;
  }
}

export async function createCrmSampleData(input: CrmSeedInput) {
  const { db, salesChief, salesStaff1, salesStaff2, director, adminChief } = input;

  const salesChiefName = salesChief.name ?? "Kepala Sales";
  const salesStaff1Name = salesStaff1.name ?? "Sales 1";
  const salesStaff2Name = salesStaff2.name ?? "Sales 2";
  const directorName = director.name ?? "Direktur";
  const adminChiefName = adminChief.name ?? "Kepala Admin";

  const organizations = [
    {
      id: "seed-crm-customer-1",
      name: "PT Sinar Ritel Nusantara",
      company: "PT Sinar Ritel Nusantara",
      email: "halo@sinarritel.co.id",
      phone: "+62217110001",
      segment: CrmCustomerSegment.SMB,
      city: "Jakarta",
      ownerName: salesChiefName,
      status: CrmCustomerStatus.ACTIVE,
      totalValue: 210000000,
      website: "https://www.sinarritel.co.id",
      annualRevenue: 2500000000,
      employeeCount: CrmEmployeeRange.ELEVEN_TO_FIFTY,
      industry: CrmIndustry.RETAIL,
      notes: "Perusahaan ritel modern dengan rencana rollout POS dan kontrol stok untuk beberapa cabang.",
      lastContactAt: new Date("2026-03-26T09:00:00+08:00"),
    },
    {
      id: "seed-crm-customer-2",
      name: "Dinas Pendidikan Kota Bandung",
      company: "Dinas Pendidikan Kota Bandung",
      email: "layanan@disdik-bandung.go.id",
      phone: "+62227110002",
      segment: CrmCustomerSegment.GOVERNMENT,
      city: "Bandung",
      ownerName: salesChiefName,
      status: CrmCustomerStatus.VIP,
      totalValue: 150000000,
      website: "https://disdik-bandung.go.id",
      annualRevenue: 0,
      employeeCount: CrmEmployeeRange.TWO_HUNDRED_ONE_TO_FIVE_HUNDRED,
      industry: CrmIndustry.GOVERNMENT,
      notes: "Prospek sektor publik untuk lisensi CRM dan dashboard layanan aduan.",
      lastContactAt: new Date("2026-03-25T14:30:00+08:00"),
    },
    {
      id: "seed-crm-customer-3",
      name: "RS Sehat Sentosa Medika",
      company: "RS Sehat Sentosa Medika",
      email: "info@rssehatsentosa.co.id",
      phone: "+62317110003",
      segment: CrmCustomerSegment.ENTERPRISE,
      city: "Surabaya",
      ownerName: salesStaff1Name,
      status: CrmCustomerStatus.ACTIVE,
      totalValue: 260000000,
      website: "https://www.rssehatsentosa.co.id",
      annualRevenue: 7800000000,
      employeeCount: CrmEmployeeRange.FIFTY_ONE_TO_TWO_HUNDRED,
      industry: CrmIndustry.HEALTHCARE,
      notes: "Rumah sakit swasta yang sedang evaluasi automasi operasional klinik dan integrasi dashboard.",
      lastContactAt: new Date("2026-03-24T11:15:00+08:00"),
    },
    {
      id: "seed-crm-customer-4",
      name: "PT Armada Logistik Timur",
      company: "PT Armada Logistik Timur",
      email: "contact@armadalogistik.co.id",
      phone: "+624117110004",
      segment: CrmCustomerSegment.ENTERPRISE,
      city: "Makassar",
      ownerName: salesStaff2Name,
      status: CrmCustomerStatus.ACTIVE,
      totalValue: 325000000,
      website: "https://www.armadalogistik.co.id",
      annualRevenue: 12400000000,
      employeeCount: CrmEmployeeRange.FIVE_HUNDRED_ONE_TO_ONE_THOUSAND,
      industry: CrmIndustry.LOGISTICS,
      notes: "Akun strategis dengan kebutuhan ERP distribusi, tracking armada, dan approval perjalanan cabang.",
      lastContactAt: new Date("2026-03-27T10:00:00+08:00"),
    },
    {
      id: "seed-crm-customer-5",
      name: "Universitas Cendekia Nusantara",
      company: "Universitas Cendekia Nusantara",
      email: "kerjasama@ucn.ac.id",
      phone: "+62247110005",
      segment: CrmCustomerSegment.EDUCATION,
      city: "Semarang",
      ownerName: directorName,
      status: CrmCustomerStatus.INACTIVE,
      totalValue: 190000000,
      website: "https://www.ucn.ac.id",
      annualRevenue: 5600000000,
      employeeCount: CrmEmployeeRange.TWO_HUNDRED_ONE_TO_FIVE_HUNDRED,
      industry: CrmIndustry.EDUCATION,
      notes: "Pipeline lama untuk portal alumni dan admissions, saat ini menunggu finalisasi anggaran.",
      lastContactAt: new Date("2026-03-18T16:30:00+08:00"),
    },
  ] as const;

  for (const organization of organizations) {
    await db.crmCustomer.upsert({
      where: { id: organization.id },
      update: {
        ...organization,
      },
      create: {
        ...organization,
      },
    });
  }

  const contacts = [
    {
      id: "seed-crm-contact-1",
      customerId: organizations[0].id,
      name: "Bimo Hartanto",
      title: "Kepala Pembelian",
      email: "bimo.hartanto@sinarritel.co.id",
      phone: "+628111120001",
      department: "Procurement",
      firstName: "Bimo",
      lastName: "Hartanto",
      gender: CrmGender.MALE,
      designation: "Kepala Pembelian",
      address: "Jl. Raya Cempaka No. 10, Jakarta",
      isPrimary: true,
      isActive: true,
      notes: "PIC utama untuk inisiatif POS dan kontrol persediaan cabang.",
    },
    {
      id: "seed-crm-contact-2",
      customerId: organizations[1].id,
      name: "Laras Ayu Putri",
      title: "Koordinator Sistem Informasi",
      email: "laras.putri@disdik-bandung.go.id",
      phone: "+628111120002",
      department: "Sistem Informasi",
      firstName: "Laras",
      lastName: "Ayu Putri",
      gender: CrmGender.FEMALE,
      designation: "Koordinator Sistem Informasi",
      address: "Jl. Wastukencana No. 2, Bandung",
      isPrimary: true,
      isActive: true,
      notes: "Membutuhkan ringkasan biaya tahunan dan skenario implementasi bertahap.",
    },
    {
      id: "seed-crm-contact-3",
      customerId: organizations[2].id,
      name: "Kevin Saputra",
      title: "Manajer Operasional Klinik",
      email: "kevin.saputra@rssehatsentosa.co.id",
      phone: "+628111120003",
      department: "Operasional",
      firstName: "Kevin",
      lastName: "Saputra",
      gender: CrmGender.MALE,
      designation: "Manajer Operasional Klinik",
      address: "Jl. Dharma Husada No. 88, Surabaya",
      isPrimary: true,
      isActive: true,
      notes: "Fokus pada efisiensi alur pasien dan approval pembelian operasional.",
    },
    {
      id: "seed-crm-contact-4",
      customerId: organizations[3].id,
      name: "Rizky Aditya",
      title: "Manajer Distribusi",
      email: "rizky.aditya@armadalogistik.co.id",
      phone: "+628111120004",
      department: "Distribusi",
      firstName: "Rizky",
      lastName: "Aditya",
      gender: CrmGender.MALE,
      designation: "Manajer Distribusi",
      address: "Jl. Perintis Kemerdekaan No. 45, Makassar",
      isPrimary: true,
      isActive: true,
      notes: "Sudah masuk tahap negosiasi akhir dan validasi kontrak rollout regional.",
    },
    {
      id: "seed-crm-contact-5",
      customerId: organizations[4].id,
      name: "Anita Permata Sari",
      title: "Kepala PMO Digital",
      email: "anita.sari@ucn.ac.id",
      phone: "+628111120005",
      department: "PMO Digital",
      firstName: "Anita",
      lastName: "Permata Sari",
      gender: CrmGender.FEMALE,
      designation: "Kepala PMO Digital",
      address: "Jl. Veteran No. 17, Semarang",
      isPrimary: false,
      isActive: true,
      notes: "Menyukai proposal yang fokus pada outcome, bukan sekadar fitur.",
    },
  ] as const;

  for (const contact of contacts) {
    await db.crmContact.upsert({
      where: { id: contact.id },
      update: {
        ...contact,
      },
      create: {
        ...contact,
      },
    });
  }

  const leads = [
    {
      id: "seed-crm-lead-1",
      customerId: organizations[0].id,
      name: "Sinta Maharani",
      company: organizations[0].company,
      email: "sinta.maharani@sinarritel.co.id",
      phone: "+62217118881",
      firstName: "Sinta",
      lastName: "Maharani",
      mobileNo: "+628121500001",
      gender: CrmGender.FEMALE,
      status: CrmLeadStatus.NEW,
      website: organizations[0].website,
      employeeCount: organizations[0].employeeCount,
      annualRevenue: organizations[0].annualRevenue,
      industry: organizations[0].industry,
      ownerId: salesStaff1.id,
      stage: mapSeedLeadStage(CrmLeadStatus.NEW),
      value: 85000000,
      probability: 20,
      source: CrmLeadSource.WEBSITE,
      priority: CrmLeadPriority.MEDIUM,
      ownerName: salesStaff1Name,
      expectedCloseDate: new Date("2026-04-15T00:00:00+08:00"),
      lastActivityAt: new Date("2026-03-28T09:00:00+08:00"),
      convertedToDealAt: null,
      notes: "Tertarik pada modul POS, approval pembelian, dan dashboard stok per cabang.",
    },
    {
      id: "seed-crm-lead-2",
      customerId: organizations[1].id,
      name: "Yusuf Ramadhan",
      company: organizations[1].company,
      email: "yusuf.ramadhan@disdik-bandung.go.id",
      phone: "+62227118882",
      firstName: "Yusuf",
      lastName: "Ramadhan",
      mobileNo: "+628121500002",
      gender: CrmGender.MALE,
      status: CrmLeadStatus.CONTACTED,
      website: organizations[1].website,
      employeeCount: organizations[1].employeeCount,
      annualRevenue: organizations[1].annualRevenue,
      industry: organizations[1].industry,
      ownerId: salesChief.id,
      stage: mapSeedLeadStage(CrmLeadStatus.CONTACTED),
      value: 145000000,
      probability: 35,
      source: CrmLeadSource.EVENT,
      priority: CrmLeadPriority.HIGH,
      ownerName: salesChiefName,
      expectedCloseDate: new Date("2026-04-22T00:00:00+08:00"),
      lastActivityAt: new Date("2026-03-25T15:30:00+08:00"),
      convertedToDealAt: null,
      notes: "Sudah menerima company profile dan meminta draft estimasi lisensi tahunan.",
    },
    {
      id: "seed-crm-lead-3",
      customerId: null,
      name: "Maya Lestari",
      company: "PT Inovasi Energi Hijau",
      email: "maya.lestari@inovasienergi.co.id",
      phone: "+62317118883",
      firstName: "Maya",
      lastName: "Lestari",
      mobileNo: "+628121500003",
      gender: CrmGender.FEMALE,
      status: CrmLeadStatus.NURTURE,
      website: "https://www.inovasienergi.co.id",
      employeeCount: CrmEmployeeRange.FIFTY_ONE_TO_TWO_HUNDRED,
      annualRevenue: 4300000000,
      industry: CrmIndustry.MANUFACTURING,
      ownerId: salesStaff1.id,
      stage: mapSeedLeadStage(CrmLeadStatus.NURTURE),
      value: 225000000,
      probability: 45,
      source: CrmLeadSource.OUTBOUND,
      priority: CrmLeadPriority.MEDIUM,
      ownerName: salesStaff1Name,
      expectedCloseDate: new Date("2026-05-02T00:00:00+08:00"),
      lastActivityAt: new Date("2026-03-26T13:00:00+08:00"),
      convertedToDealAt: null,
      notes: "Masih tahap edukasi kebutuhan ERP untuk divisi procurement dan maintenance.",
    },
    {
      id: "seed-crm-lead-4",
      customerId: organizations[2].id,
      name: "Riko Saptono",
      company: organizations[2].company,
      email: "riko.saptono@rssehatsentosa.co.id",
      phone: "+62317118884",
      firstName: "Riko",
      lastName: "Saptono",
      mobileNo: "+628121500004",
      gender: CrmGender.MALE,
      status: CrmLeadStatus.QUALIFIED,
      website: organizations[2].website,
      employeeCount: organizations[2].employeeCount,
      annualRevenue: organizations[2].annualRevenue,
      industry: organizations[2].industry,
      ownerId: salesChief.id,
      stage: mapSeedLeadStage(CrmLeadStatus.QUALIFIED),
      value: 260000000,
      probability: 70,
      source: CrmLeadSource.REFERRAL,
      priority: CrmLeadPriority.HIGH,
      ownerName: salesChiefName,
      expectedCloseDate: new Date("2026-04-10T00:00:00+08:00"),
      lastActivityAt: new Date("2026-03-27T11:00:00+08:00"),
      convertedToDealAt: null,
      notes: "Kebutuhan sudah jelas, tinggal finalisasi ruang lingkup pilot project.",
    },
    {
      id: "seed-crm-lead-5",
      customerId: organizations[3].id,
      name: "Gilang Prakoso",
      company: organizations[3].company,
      email: "gilang.prakoso@armadalogistik.co.id",
      phone: "+62411718885",
      firstName: "Gilang",
      lastName: "Prakoso",
      mobileNo: "+628121500005",
      gender: CrmGender.MALE,
      status: CrmLeadStatus.CONVERTED,
      website: organizations[3].website,
      employeeCount: organizations[3].employeeCount,
      annualRevenue: organizations[3].annualRevenue,
      industry: organizations[3].industry,
      ownerId: salesStaff2.id,
      stage: mapSeedLeadStage(CrmLeadStatus.CONVERTED),
      value: 325000000,
      probability: 100,
      source: CrmLeadSource.PARTNER,
      priority: CrmLeadPriority.HIGH,
      ownerName: salesStaff2Name,
      expectedCloseDate: new Date("2026-03-20T00:00:00+08:00"),
      lastActivityAt: new Date("2026-03-21T10:30:00+08:00"),
      convertedToDealAt: new Date("2026-03-19T10:00:00+08:00"),
      notes: "Lead berhasil dikonversi menjadi deal rollout ERP distribusi regional.",
    },
    {
      id: "seed-crm-lead-6",
      customerId: null,
      name: "Novi Amelia",
      company: "Koperasi Karya Mandiri",
      email: "novi.amelia@koperasikarya.co.id",
      phone: "+62217118886",
      firstName: "Novi",
      lastName: "Amelia",
      mobileNo: "+628121500006",
      gender: CrmGender.FEMALE,
      status: CrmLeadStatus.UNQUALIFIED,
      website: "https://www.koperasikarya.co.id",
      employeeCount: CrmEmployeeRange.ELEVEN_TO_FIFTY,
      annualRevenue: 950000000,
      industry: CrmIndustry.FINANCE,
      ownerId: salesStaff1.id,
      stage: mapSeedLeadStage(CrmLeadStatus.UNQUALIFIED),
      value: 35000000,
      probability: 5,
      source: CrmLeadSource.WEBSITE,
      priority: CrmLeadPriority.LOW,
      ownerName: salesStaff1Name,
      expectedCloseDate: null,
      lastActivityAt: new Date("2026-03-18T09:30:00+08:00"),
      convertedToDealAt: null,
      notes: "Tidak memenuhi minimum budget dan belum memiliki sponsor internal yang kuat.",
    },
    {
      id: "seed-crm-lead-7",
      customerId: null,
      name: "Asep Mulyana",
      company: "CV Jaringan Cepat",
      email: "asep.mulyana@jaringancepat.co.id",
      phone: "+62227118887",
      firstName: "Asep",
      lastName: "Mulyana",
      mobileNo: "+628121500007",
      gender: CrmGender.MALE,
      status: CrmLeadStatus.JUNK,
      website: "https://www.jaringancepat.co.id",
      employeeCount: CrmEmployeeRange.ONE_TO_TEN,
      annualRevenue: 250000000,
      industry: CrmIndustry.TECHNOLOGY,
      ownerId: salesStaff2.id,
      stage: mapSeedLeadStage(CrmLeadStatus.JUNK),
      value: 15000000,
      probability: 0,
      source: CrmLeadSource.OUTBOUND,
      priority: CrmLeadPriority.LOW,
      ownerName: salesStaff2Name,
      expectedCloseDate: null,
      lastActivityAt: new Date("2026-03-17T15:00:00+08:00"),
      convertedToDealAt: null,
      notes: "Data lead tidak valid dan kontak tidak pernah merespons.",
    },
  ] as const;

  for (const lead of leads) {
    await db.crmLead.upsert({
      where: { id: lead.id },
      update: {
        ...lead,
      },
      create: {
        ...lead,
      },
    });
  }

  const deals = [
    {
      id: "seed-crm-deal-1",
      customerId: organizations[3].id,
      contactId: contacts[3].id,
      leadId: leads[4].id,
      title: "Implementasi ERP Armada Regional",
      company: organizations[3].company,
      ownerName: salesStaff2Name,
      ownerId: salesStaff2.id,
      status: CrmDealStatus.WON,
      website: organizations[3].website,
      employeeCount: organizations[3].employeeCount,
      annualRevenue: organizations[3].annualRevenue,
      industry: organizations[3].industry,
      firstName: contacts[3].firstName,
      lastName: contacts[3].lastName,
      primaryEmail: contacts[3].email,
      primaryMobileNo: contacts[3].phone,
      gender: contacts[3].gender,
      stage: mapSeedDealStage(CrmDealStatus.WON),
      value: 325000000,
      probability: 100,
      source: CrmLeadSource.PARTNER,
      expectedCloseDate: new Date("2026-03-20T00:00:00+08:00"),
      closedAt: new Date("2026-03-21T15:00:00+08:00"),
      lostReason: null,
      notes: "Kontrak sudah ditandatangani, kickoff project dijadwalkan pekan depan.",
      lastActivityAt: new Date("2026-03-21T15:00:00+08:00"),
    },
    {
      id: "seed-crm-deal-2",
      customerId: organizations[1].id,
      contactId: contacts[1].id,
      leadId: null,
      title: "Lisensi CRM Dinas Pendidikan",
      company: organizations[1].company,
      ownerName: salesChiefName,
      ownerId: salesChief.id,
      status: CrmDealStatus.QUALIFICATION,
      website: organizations[1].website,
      employeeCount: organizations[1].employeeCount,
      annualRevenue: organizations[1].annualRevenue,
      industry: organizations[1].industry,
      firstName: contacts[1].firstName,
      lastName: contacts[1].lastName,
      primaryEmail: contacts[1].email,
      primaryMobileNo: contacts[1].phone,
      gender: contacts[1].gender,
      stage: mapSeedDealStage(CrmDealStatus.QUALIFICATION),
      value: 150000000,
      probability: 25,
      source: CrmLeadSource.EVENT,
      expectedCloseDate: new Date("2026-05-12T00:00:00+08:00"),
      closedAt: null,
      lostReason: null,
      notes: "Masih tahap pengumpulan kebutuhan dan penyesuaian skema pengadaan pemerintah.",
      lastActivityAt: new Date("2026-03-25T14:30:00+08:00"),
    },
    {
      id: "seed-crm-deal-3",
      customerId: organizations[2].id,
      contactId: contacts[2].id,
      leadId: null,
      title: "Automasi Operasional Klinik",
      company: organizations[2].company,
      ownerName: salesStaff1Name,
      ownerId: salesStaff1.id,
      status: CrmDealStatus.DEMO_MAKING,
      website: organizations[2].website,
      employeeCount: organizations[2].employeeCount,
      annualRevenue: organizations[2].annualRevenue,
      industry: organizations[2].industry,
      firstName: contacts[2].firstName,
      lastName: contacts[2].lastName,
      primaryEmail: contacts[2].email,
      primaryMobileNo: contacts[2].phone,
      gender: contacts[2].gender,
      stage: mapSeedDealStage(CrmDealStatus.DEMO_MAKING),
      value: 260000000,
      probability: 45,
      source: CrmLeadSource.REFERRAL,
      expectedCloseDate: new Date("2026-04-18T00:00:00+08:00"),
      closedAt: null,
      lostReason: null,
      notes: "Demo onsite akan difokuskan ke dashboard operasional dan approval pembelian farmasi.",
      lastActivityAt: new Date("2026-03-24T11:30:00+08:00"),
    },
    {
      id: "seed-crm-deal-4",
      customerId: organizations[4].id,
      contactId: contacts[4].id,
      leadId: null,
      title: "Portal Alumni dan Admissions",
      company: organizations[4].company,
      ownerName: salesChiefName,
      ownerId: salesChief.id,
      status: CrmDealStatus.PROPOSAL_QUOTATION,
      website: organizations[4].website,
      employeeCount: organizations[4].employeeCount,
      annualRevenue: organizations[4].annualRevenue,
      industry: organizations[4].industry,
      firstName: contacts[4].firstName,
      lastName: contacts[4].lastName,
      primaryEmail: contacts[4].email,
      primaryMobileNo: contacts[4].phone,
      gender: contacts[4].gender,
      stage: mapSeedDealStage(CrmDealStatus.PROPOSAL_QUOTATION),
      value: 190000000,
      probability: 60,
      source: CrmLeadSource.WEBSITE,
      expectedCloseDate: new Date("2026-04-30T00:00:00+08:00"),
      closedAt: null,
      lostReason: null,
      notes: "Proposal sedang direview oleh tim PMO dan biro keuangan kampus.",
      lastActivityAt: new Date("2026-03-23T10:00:00+08:00"),
    },
    {
      id: "seed-crm-deal-5",
      customerId: null,
      contactId: null,
      leadId: null,
      title: "ERP Procurement Energi Hijau",
      company: "PT Inovasi Energi Hijau",
      ownerName: salesStaff1Name,
      ownerId: salesStaff1.id,
      status: CrmDealStatus.NEGOTIATION,
      website: "https://www.inovasienergi.co.id",
      employeeCount: CrmEmployeeRange.FIFTY_ONE_TO_TWO_HUNDRED,
      annualRevenue: 4300000000,
      industry: CrmIndustry.MANUFACTURING,
      firstName: "Maya",
      lastName: "Lestari",
      primaryEmail: "maya.lestari@inovasienergi.co.id",
      primaryMobileNo: "+628121500003",
      gender: CrmGender.FEMALE,
      stage: mapSeedDealStage(CrmDealStatus.NEGOTIATION),
      value: 225000000,
      probability: 75,
      source: CrmLeadSource.OUTBOUND,
      expectedCloseDate: new Date("2026-04-25T00:00:00+08:00"),
      closedAt: null,
      lostReason: null,
      notes: "Poin negosiasi utama ada pada skema pembayaran bertahap dan SLA support.",
      lastActivityAt: new Date("2026-03-26T14:00:00+08:00"),
    },
    {
      id: "seed-crm-deal-6",
      customerId: organizations[0].id,
      contactId: contacts[0].id,
      leadId: null,
      title: "Rollout POS Cabang Jawa",
      company: organizations[0].company,
      ownerName: salesStaff2Name,
      ownerId: salesStaff2.id,
      status: CrmDealStatus.READY_TO_CLOSE,
      website: organizations[0].website,
      employeeCount: organizations[0].employeeCount,
      annualRevenue: organizations[0].annualRevenue,
      industry: organizations[0].industry,
      firstName: contacts[0].firstName,
      lastName: contacts[0].lastName,
      primaryEmail: contacts[0].email,
      primaryMobileNo: contacts[0].phone,
      gender: contacts[0].gender,
      stage: mapSeedDealStage(CrmDealStatus.READY_TO_CLOSE),
      value: 210000000,
      probability: 90,
      source: CrmLeadSource.WEBSITE,
      expectedCloseDate: new Date("2026-04-03T00:00:00+08:00"),
      closedAt: null,
      lostReason: null,
      notes: "PO final sedang disiapkan, tim customer meminta jadwal kickoff yang lebih cepat.",
      lastActivityAt: new Date("2026-03-27T09:00:00+08:00"),
    },
    {
      id: "seed-crm-deal-7",
      customerId: null,
      contactId: null,
      leadId: null,
      title: "Sistem Monitoring Properti",
      company: "CV Mitra Sarana Properti",
      ownerName: salesChiefName,
      ownerId: salesChief.id,
      status: CrmDealStatus.LOST,
      website: "https://www.mitrasaranaproperti.co.id",
      employeeCount: CrmEmployeeRange.ELEVEN_TO_FIFTY,
      annualRevenue: 1750000000,
      industry: CrmIndustry.OTHER,
      firstName: "Farhan",
      lastName: "Yusuf",
      primaryEmail: "farhan.yusuf@mitrasaranaproperti.co.id",
      primaryMobileNo: "+628121500008",
      gender: CrmGender.MALE,
      stage: mapSeedDealStage(CrmDealStatus.LOST),
      value: 98000000,
      probability: 0,
      source: CrmLeadSource.REFERRAL,
      expectedCloseDate: new Date("2026-03-18T00:00:00+08:00"),
      closedAt: new Date("2026-03-18T17:00:00+08:00"),
      lostReason: "Anggaran dialihkan ke proyek lain dan keputusan ditunda sampai tahun depan.",
      notes: "Tetap jaga hubungan baik untuk peluang tahun berikutnya.",
      lastActivityAt: new Date("2026-03-18T17:00:00+08:00"),
    },
  ] as const;

  for (const deal of deals) {
    await db.crmDeal.upsert({
      where: { id: deal.id },
      update: {
        ...deal,
      },
      create: {
        ...deal,
      },
    });
  }

  const conversations = [
    {
      id: "seed-crm-conversation-1",
      customerId: organizations[0].id,
      leadId: leads[0].id,
      dealId: null,
      subject: "Tindak lanjut kebutuhan POS cabang",
      ownerName: salesStaff1Name,
      status: CrmConversationStatus.OPEN,
      lastMessageAt: new Date("2026-03-26T09:15:00+08:00"),
      lastMessagePreview: "Mohon kirimkan demo alur stok per cabang.",
    },
    {
      id: "seed-crm-conversation-2",
      customerId: organizations[1].id,
      leadId: null,
      dealId: deals[1].id,
      subject: "Diskusi lisensi dan alokasi anggaran",
      ownerName: salesChiefName,
      status: CrmConversationStatus.WAITING_REPLY,
      lastMessageAt: new Date("2026-03-25T14:45:00+08:00"),
      lastMessagePreview: "Kami menunggu format rincian biaya tahunan.",
    },
    {
      id: "seed-crm-conversation-3",
      customerId: organizations[3].id,
      leadId: leads[4].id,
      dealId: deals[0].id,
      subject: "Negosiasi kontrak rollout ERP distribusi",
      ownerName: salesStaff2Name,
      status: CrmConversationStatus.CLOSED,
      lastMessageAt: new Date("2026-03-21T15:30:00+08:00"),
      lastMessagePreview: "Kontrak final sudah kami tanda tangani.",
    },
    {
      id: "seed-crm-conversation-4",
      customerId: organizations[2].id,
      leadId: null,
      dealId: deals[2].id,
      subject: "Persiapan demo operasional klinik",
      ownerName: salesStaff1Name,
      status: CrmConversationStatus.OPEN,
      lastMessageAt: new Date("2026-03-24T11:45:00+08:00"),
      lastMessagePreview: "Silakan kirim skenario demo untuk unit rawat jalan.",
    },
    {
      id: "seed-crm-conversation-5",
      customerId: organizations[4].id,
      leadId: null,
      dealId: deals[3].id,
      subject: "Review proposal portal kampus",
      ownerName: salesChiefName,
      status: CrmConversationStatus.WAITING_REPLY,
      lastMessageAt: new Date("2026-03-23T10:15:00+08:00"),
      lastMessagePreview: "Proposal kami review bersama tim PMO pekan ini.",
    },
  ] as const;

  for (const conversation of conversations) {
    await db.crmConversation.upsert({
      where: { id: conversation.id },
      update: {
        ...conversation,
      },
      create: {
        ...conversation,
      },
    });
  }

  const messages = [
    {
      id: "seed-crm-message-1",
      conversationId: conversations[0].id,
      status: CrmMessageStatus.RECEIVED,
      senderName: "Sinta Maharani",
      body: "Mohon kirimkan contoh dashboard stok per cabang dan alur approval pembelian.",
      sentAt: new Date("2026-03-26T09:15:00+08:00"),
    },
    {
      id: "seed-crm-message-2",
      conversationId: conversations[1].id,
      status: CrmMessageStatus.SENT,
      senderName: salesChiefName,
      body: "Kami lampirkan struktur lisensi tahunan dan skenario implementasi bertahap.",
      sentAt: new Date("2026-03-25T14:45:00+08:00"),
    },
    {
      id: "seed-crm-message-3",
      conversationId: conversations[2].id,
      status: CrmMessageStatus.RECEIVED,
      senderName: "Rizky Aditya",
      body: "Kontrak final sudah kami tanda tangani, mohon lanjutkan persiapan kickoff.",
      sentAt: new Date("2026-03-21T15:30:00+08:00"),
    },
    {
      id: "seed-crm-message-4",
      conversationId: conversations[3].id,
      status: CrmMessageStatus.NOTE,
      senderName: salesStaff1Name,
      body: "Customer meminta demo fokus ke operasional rawat jalan dan pharmacy approval.",
      sentAt: new Date("2026-03-24T11:45:00+08:00"),
    },
    {
      id: "seed-crm-message-5",
      conversationId: conversations[4].id,
      status: CrmMessageStatus.SENT,
      senderName: salesChiefName,
      body: "Kami tindak lanjuti revisi proposal sesuai masukan PMO dan biro keuangan.",
      sentAt: new Date("2026-03-23T10:15:00+08:00"),
    },
  ] as const;

  for (const message of messages) {
    await db.crmMessage.upsert({
      where: { id: message.id },
      update: {
        ...message,
      },
      create: {
        ...message,
      },
    });
  }

  const tasks = [
    {
      id: "seed-crm-task-1",
      leadId: leads[0].id,
      dealId: null,
      title: "Kirim materi pengenalan produk",
      description: "Kirim deck singkat untuk modul POS, approval, dan dashboard stok cabang.",
      status: CrmTaskStatus.OPEN,
      assigneeId: salesStaff1.id,
      assigneeName: salesStaff1Name,
      dueDate: new Date("2026-04-02T00:00:00+08:00"),
      priority: CrmTaskPriority.MEDIUM,
    },
    {
      id: "seed-crm-task-2",
      leadId: leads[3].id,
      dealId: null,
      title: "Jadwalkan demo onsite dengan tim klinik",
      description: "Koordinasikan slot demo untuk operasional, farmasi, dan keuangan.",
      status: CrmTaskStatus.IN_PROGRESS,
      assigneeId: salesChief.id,
      assigneeName: salesChiefName,
      dueDate: new Date("2026-03-30T00:00:00+08:00"),
      priority: CrmTaskPriority.HIGH,
    },
    {
      id: "seed-crm-task-3",
      leadId: leads[4].id,
      dealId: null,
      title: "Finalisasi dokumen handover deal",
      description: "Pastikan seluruh catatan lead dipindahkan ke deal implementasi.",
      status: CrmTaskStatus.COMPLETED,
      assigneeId: salesStaff2.id,
      assigneeName: salesStaff2Name,
      dueDate: new Date("2026-03-20T00:00:00+08:00"),
      priority: CrmTaskPriority.MEDIUM,
    },
    {
      id: "seed-crm-task-4",
      leadId: null,
      dealId: deals[1].id,
      title: "Siapkan proposal harga awal",
      description: "Buat opsi lisensi tahunan dan layanan implementasi per fase.",
      status: CrmTaskStatus.OPEN,
      assigneeId: salesChief.id,
      assigneeName: salesChiefName,
      dueDate: new Date("2026-04-05T00:00:00+08:00"),
      priority: CrmTaskPriority.HIGH,
    },
    {
      id: "seed-crm-task-5",
      leadId: null,
      dealId: deals[4].id,
      title: "Tindak lanjuti hasil negosiasi legal",
      description: "Review ulang pasal termin pembayaran dan ruang lingkup support.",
      status: CrmTaskStatus.CANCELLED,
      assigneeId: salesStaff1.id,
      assigneeName: salesStaff1Name,
      dueDate: new Date("2026-03-28T00:00:00+08:00"),
      priority: CrmTaskPriority.MEDIUM,
    },
    {
      id: "seed-crm-task-6",
      leadId: null,
      dealId: deals[5].id,
      title: "Verifikasi PO dan jadwal kickoff",
      description: "Sinkronkan jadwal implementasi awal dan kesiapan data master cabang.",
      status: CrmTaskStatus.COMPLETED,
      assigneeId: salesStaff2.id,
      assigneeName: salesStaff2Name,
      dueDate: new Date("2026-03-26T00:00:00+08:00"),
      priority: CrmTaskPriority.HIGH,
    },
  ] as const;

  for (const task of tasks) {
    await db.crmTask.upsert({
      where: { id: task.id },
      update: {
        ...task,
      },
      create: {
        ...task,
      },
    });
  }

  const notes = [
    {
      id: "seed-crm-note-1",
      leadId: leads[0].id,
      dealId: null,
      title: "Catatan kebutuhan awal",
      content: "Customer meminta fokus pada kontrol stok per cabang dan approval pembelian cepat.",
      writerId: salesStaff1.id,
      writerName: salesStaff1Name,
    },
    {
      id: "seed-crm-note-2",
      leadId: leads[3].id,
      dealId: null,
      title: "Ringkasan discovery",
      content: "Tim operasional sudah menyetujui skenario pilot, tinggal validasi kebutuhan dashboard.",
      writerId: salesChief.id,
      writerName: salesChiefName,
    },
    {
      id: "seed-crm-note-3",
      leadId: leads[4].id,
      dealId: null,
      title: "Catatan konversi lead",
      content: "Lead dikonversi setelah customer menyetujui ruang lingkup regional dan jadwal implementasi.",
      writerId: salesStaff2.id,
      writerName: salesStaff2Name,
    },
    {
      id: "seed-crm-note-4",
      leadId: null,
      dealId: deals[1].id,
      title: "Masukan proposal pemerintah",
      content: "Perlu lampirkan skema lisensi tahunan, support, dan training pengguna pada proposal final.",
      writerId: director.id,
      writerName: directorName,
    },
    {
      id: "seed-crm-note-5",
      leadId: null,
      dealId: deals[4].id,
      title: "Catatan negosiasi legal",
      content: "Customer meminta termin pembayaran 40-30-30 dan SLA respon maksimal 2 jam.",
      writerId: salesStaff1.id,
      writerName: salesStaff1Name,
    },
    {
      id: "seed-crm-note-6",
      leadId: null,
      dealId: deals[6].id,
      title: "Evaluasi deal kalah",
      content: "Peluang kalah karena prioritas anggaran customer bergeser ke proyek internal yang lebih mendesak.",
      writerId: adminChief.id,
      writerName: adminChiefName,
    },
  ] as const;

  for (const note of notes) {
    await db.crmNote.upsert({
      where: { id: note.id },
      update: {
        ...note,
      },
      create: {
        ...note,
      },
    });
  }

  const attachments = [
    {
      id: "seed-crm-attachment-1",
      leadId: leads[0].id,
      dealId: null,
      filename: "brief-kebutuhan-pos.pdf",
      originalName: "brief-kebutuhan-pos.pdf",
      mimeType: "application/pdf",
      fileSize: 148576,
      storageUrl: buildSeedDataUrl("Brief kebutuhan POS"),
      storageProvider: "inline-seed",
    },
    {
      id: "seed-crm-attachment-2",
      leadId: leads[3].id,
      dealId: null,
      filename: "daftar-kebutuhan-klinik.xlsx",
      originalName: "daftar-kebutuhan-klinik.xlsx",
      mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      fileSize: 98234,
      storageUrl: buildSeedDataUrl("Daftar kebutuhan klinik"),
      storageProvider: "inline-seed",
    },
    {
      id: "seed-crm-attachment-3",
      leadId: null,
      dealId: deals[0].id,
      filename: "kontrak-rollout-erp.pdf",
      originalName: "kontrak-rollout-erp.pdf",
      mimeType: "application/pdf",
      fileSize: 223410,
      storageUrl: buildSeedDataUrl("Kontrak rollout ERP"),
      storageProvider: "inline-seed",
    },
    {
      id: "seed-crm-attachment-4",
      leadId: null,
      dealId: deals[4].id,
      filename: "draft-mou-erp-energi.docx",
      originalName: "draft-mou-erp-energi.docx",
      mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      fileSize: 124560,
      storageUrl: buildSeedDataUrl("Draft MOU ERP Energi"),
      storageProvider: "inline-seed",
    },
    {
      id: "seed-crm-attachment-5",
      leadId: null,
      dealId: deals[6].id,
      filename: "evaluasi-deal-kalah.pdf",
      originalName: "evaluasi-deal-kalah.pdf",
      mimeType: "application/pdf",
      fileSize: 66542,
      storageUrl: buildSeedDataUrl("Evaluasi deal kalah"),
      storageProvider: "inline-seed",
    },
  ] as const;

  for (const attachment of attachments) {
    await db.crmRecordAttachment.upsert({
      where: { id: attachment.id },
      update: {
        ...attachment,
      },
      create: {
        ...attachment,
      },
    });
  }

  const activities = [
    {
      id: "seed-crm-activity-1",
      customerId: organizations[0].id,
      leadId: leads[0].id,
      dealId: null,
      conversationId: conversations[0].id,
      messageId: messages[0].id,
      title: "Email kebutuhan POS diterima",
      description: "Customer mengirim daftar kebutuhan awal untuk dashboard stok dan approval pembelian.",
      type: CrmActivityType.EMAIL,
      ownerName: salesStaff1Name,
      scheduledAt: new Date("2026-03-26T09:15:00+08:00"),
      completedAt: new Date("2026-03-26T09:15:00+08:00"),
    },
    {
      id: "seed-crm-activity-2",
      customerId: organizations[1].id,
      leadId: null,
      dealId: deals[1].id,
      conversationId: conversations[1].id,
      messageId: messages[1].id,
      title: "Proposal lisensi awal dikirim",
      description: "Tim sales mengirimkan struktur lisensi tahunan dan tahapan implementasi.",
      type: CrmActivityType.MEETING,
      ownerName: salesChiefName,
      scheduledAt: new Date("2026-03-25T14:45:00+08:00"),
      completedAt: new Date("2026-03-25T15:30:00+08:00"),
    },
    {
      id: "seed-crm-activity-3",
      customerId: organizations[3].id,
      leadId: leads[4].id,
      dealId: deals[0].id,
      conversationId: conversations[2].id,
      messageId: messages[2].id,
      title: "Lead dikonversi dan deal dimenangkan",
      description: "Customer menandatangani kontrak rollout ERP distribusi regional.",
      type: CrmActivityType.STAGE_CHANGE,
      ownerName: salesStaff2Name,
      scheduledAt: new Date("2026-03-21T15:30:00+08:00"),
      completedAt: new Date("2026-03-21T15:30:00+08:00"),
    },
    {
      id: "seed-crm-activity-4",
      customerId: organizations[2].id,
      leadId: null,
      dealId: deals[2].id,
      conversationId: conversations[3].id,
      messageId: messages[3].id,
      title: "Catatan demo operasional disimpan",
      description: "Demo akan difokuskan ke unit rawat jalan, pharmacy, dan approval pembelian.",
      type: CrmActivityType.NOTE,
      ownerName: salesStaff1Name,
      scheduledAt: new Date("2026-03-24T11:45:00+08:00"),
      completedAt: new Date("2026-03-24T11:45:00+08:00"),
    },
    {
      id: "seed-crm-activity-5",
      customerId: organizations[2].id,
      leadId: leads[3].id,
      dealId: null,
      conversationId: null,
      messageId: null,
      title: "Panggilan validasi kebutuhan",
      description: "Validasi kebutuhan dashboard operasional dan skema pilot project selesai.",
      type: CrmActivityType.CALL,
      ownerName: salesChiefName,
      scheduledAt: new Date("2026-03-27T11:00:00+08:00"),
      completedAt: new Date("2026-03-27T11:30:00+08:00"),
    },
    {
      id: "seed-crm-activity-6",
      customerId: null,
      leadId: null,
      dealId: deals[4].id,
      conversationId: null,
      messageId: null,
      title: "Follow up hasil negosiasi legal",
      description: "Menunggu revisi final MOU dari pihak customer sebelum lanjut ke closing.",
      type: CrmActivityType.FOLLOW_UP,
      ownerName: salesStaff1Name,
      scheduledAt: new Date("2026-03-26T14:00:00+08:00"),
      completedAt: null,
    },
    {
      id: "seed-crm-activity-7",
      customerId: organizations[3].id,
      leadId: null,
      dealId: deals[0].id,
      conversationId: null,
      messageId: null,
      title: "Kontrak rollout diunggah",
      description: "Lampiran kontrak final tersedia pada detail deal untuk kebutuhan audit internal.",
      type: CrmActivityType.ATTACHMENT,
      ownerName: adminChiefName,
      scheduledAt: new Date("2026-03-21T16:00:00+08:00"),
      completedAt: new Date("2026-03-21T16:00:00+08:00"),
    },
    {
      id: "seed-crm-activity-8",
      customerId: organizations[0].id,
      leadId: leads[0].id,
      dealId: null,
      conversationId: null,
      messageId: null,
      title: "Tugas follow up dibuat",
      description: "Tim sales membuat tugas pengiriman deck produk untuk tindak lanjut lead baru.",
      type: CrmActivityType.TASK,
      ownerName: salesStaff1Name,
      scheduledAt: new Date("2026-03-28T09:00:00+08:00"),
      completedAt: null,
    },
  ] as const;

  for (const activity of activities) {
    await db.crmActivity.upsert({
      where: { id: activity.id },
      update: {
        ...activity,
      },
      create: {
        ...activity,
      },
    });
  }
}




